package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private int id;
	private String name;
	private Integer province;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public City() {
	}

	public City(int id) {
		this.id = id;
	}

	public City(int id, String name, Integer province, Set<Customer> customers) {
		this.id = id;
		this.name = name;
		this.province = province;
		this.customers = customers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getProvince() {
		return this.province;
	}

	public void setProvince(Integer province) {
		this.province = province;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
