package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int id;
	private String name;
	private String memo;
	private String address;
	private String telNumber;
	private String mobileNumber;
	private String fax;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Company() {
	}

	public Company(int id) {
		this.id = id;
	}

	public Company(int id, String name, String memo, String address,
			String telNumber, String mobileNumber, String fax,
			Set<Customer> customers) {
		this.id = id;
		this.name = name;
		this.memo = memo;
		this.address = address;
		this.telNumber = telNumber;
		this.mobileNumber = mobileNumber;
		this.fax = fax;
		this.customers = customers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelNumber() {
		return this.telNumber;
	}

	public void setTelNumber(String telNumber) {
		this.telNumber = telNumber;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
