package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int id;
	private City city;
	private Company company;
	private String name;
	private String telNumber;
	private String mobileNumber;
	private String address;
	private String saleBillInfo;
	private String principal;
	private Set<SaleOrder> saleOrders = new HashSet<SaleOrder>(0);
	private Set<ProductModal> productModals = new HashSet<ProductModal>(0);

	public Customer() {
	}

	public Customer(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Customer(int id, City city, Company company, String name,
			String telNumber, String mobileNumber, String address,
			String saleBillInfo, String principal, Set<SaleOrder> saleOrders,
			Set<ProductModal> productModals) {
		this.id = id;
		this.city = city;
		this.company = company;
		this.name = name;
		this.telNumber = telNumber;
		this.mobileNumber = mobileNumber;
		this.address = address;
		this.saleBillInfo = saleBillInfo;
		this.principal = principal;
		this.saleOrders = saleOrders;
		this.productModals = productModals;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTelNumber() {
		return this.telNumber;
	}

	public void setTelNumber(String telNumber) {
		this.telNumber = telNumber;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSaleBillInfo() {
		return this.saleBillInfo;
	}

	public void setSaleBillInfo(String saleBillInfo) {
		this.saleBillInfo = saleBillInfo;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public Set<SaleOrder> getSaleOrders() {
		return this.saleOrders;
	}

	public void setSaleOrders(Set<SaleOrder> saleOrders) {
		this.saleOrders = saleOrders;
	}

	public Set<ProductModal> getProductModals() {
		return this.productModals;
	}

	public void setProductModals(Set<ProductModal> productModals) {
		this.productModals = productModals;
	}

}
