package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * KisRole generated by hbm2java
 */
public class KisRole implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set<KisUser> kisUsers = new HashSet<KisUser>(0);

	public KisRole() {
	}

	public KisRole(int id) {
		this.id = id;
	}

	public KisRole(int id, String name, String description, Set<KisUser> kisUsers) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.kisUsers = kisUsers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<KisUser> getKisUsers() {
		return this.kisUsers;
	}

	public void setKisUsers(Set<KisUser> kisUsers) {
		this.kisUsers = kisUsers;
	}

}
