package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KisUser generated by hbm2java
 */
public class KisUser implements java.io.Serializable {

	private int id;
	private KisRole kisRole;
	private String name;
	private String passwd;
	private Date updateTime;
	private String showName;
	private Set<SaleOrder> saleOrders = new HashSet<SaleOrder>(0);

	public KisUser() {
	}

	public KisUser(int id, String name, String passwd) {
		this.id = id;
		this.name = name;
		this.passwd = passwd;
	}

	public KisUser(int id, KisRole kisRole, String name, String passwd,
			Date updateTime, String showName, Set<SaleOrder> saleOrders) {
		this.id = id;
		this.kisRole = kisRole;
		this.name = name;
		this.passwd = passwd;
		this.updateTime = updateTime;
		this.showName = showName;
		this.saleOrders = saleOrders;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public KisRole getKisRole() {
		return this.kisRole;
	}

	public void setKisRole(KisRole kisRole) {
		this.kisRole = kisRole;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getShowName() {
		return this.showName;
	}

	public void setShowName(String showName) {
		this.showName = showName;
	}

	public Set<SaleOrder> getSaleOrders() {
		return this.saleOrders;
	}

	public void setSaleOrders(Set<SaleOrder> saleOrders) {
		this.saleOrders = saleOrders;
	}

}
