package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductModal generated by hbm2java
 */
public class ProductModal implements java.io.Serializable {

	private int id;
	private Customer customer;
	private ProductCategory productCategory;
	private ProductUnits productUnits;
	private String name;
	private String description;
	private BigDecimal suggestUnitPrice;
	private Set<SaleOrderItem> saleOrderItems = new HashSet<SaleOrderItem>(0);

	public ProductModal() {
	}

	public ProductModal(int id, Customer customer,
			ProductCategory productCategory, String name) {
		this.id = id;
		this.customer = customer;
		this.productCategory = productCategory;
		this.name = name;
	}

	public ProductModal(int id, Customer customer,
			ProductCategory productCategory, ProductUnits productUnits,
			String name, String description, BigDecimal suggestUnitPrice,
			Set<SaleOrderItem> saleOrderItems) {
		this.id = id;
		this.customer = customer;
		this.productCategory = productCategory;
		this.productUnits = productUnits;
		this.name = name;
		this.description = description;
		this.suggestUnitPrice = suggestUnitPrice;
		this.saleOrderItems = saleOrderItems;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	public ProductUnits getProductUnits() {
		return this.productUnits;
	}

	public void setProductUnits(ProductUnits productUnits) {
		this.productUnits = productUnits;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getSuggestUnitPrice() {
		return this.suggestUnitPrice;
	}

	public void setSuggestUnitPrice(BigDecimal suggestUnitPrice) {
		this.suggestUnitPrice = suggestUnitPrice;
	}

	public Set<SaleOrderItem> getSaleOrderItems() {
		return this.saleOrderItems;
	}

	public void setSaleOrderItems(Set<SaleOrderItem> saleOrderItems) {
		this.saleOrderItems = saleOrderItems;
	}

}
