package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategory generated by hbm2java
 */
public class ProductCategory implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set<ProductModal> productModals = new HashSet<ProductModal>(0);

	public ProductCategory() {
	}

	public ProductCategory(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public ProductCategory(int id, String name, String desc,
			Set<ProductModal> productModals) {
		this.id = id;
		this.name = name;
		this.description = desc;
		this.productModals = productModals;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ProductModal> getProductModals() {
		return this.productModals;
	}

	public void setProductModals(Set<ProductModal> productModals) {
		this.productModals = productModals;
	}

}
