package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductUnits generated by hbm2java
 */
public class ProductUnits implements java.io.Serializable {

	private int id;
	private String cnName;
	private String enName;
	private String description;
	private Set<ProductModal> productModals = new HashSet<ProductModal>(0);

	public ProductUnits() {
	}

	public ProductUnits(int id, String cnName, String enName) {
		this.id = id;
		this.cnName = cnName;
		this.enName = enName;
	}

	public ProductUnits(int id, String cnName, String enName, String description,
			Set<ProductModal> productModals) {
		this.id = id;
		this.cnName = cnName;
		this.enName = enName;
		this.description = description;
		this.productModals = productModals;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCnName() {
		return this.cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ProductModal> getProductModals() {
		return this.productModals;
	}

	public void setProductModals(Set<ProductModal> productModals) {
		this.productModals = productModals;
	}

}
