package kis.entity;

// Generated 2015-7-17 20:11:35 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * SaleOrderItem generated by hbm2java
 */
public class SaleOrderItem implements java.io.Serializable {

	private int id;
	private ProductModal productModal;
	private SaleOrder saleOrder;
	private BigDecimal quantity;
	private BigDecimal unitPrice;
	private BigDecimal sum;
	private String memo;
	private Integer serialNumber;
	private String productModalText;
	private String productCategoryText;
	private String productUnitsText;

	public SaleOrderItem() {
	}

	public SaleOrderItem(int id, BigDecimal quantity) {
		this.id = id;
		this.quantity = quantity;
	}

	public SaleOrderItem(int id, ProductModal productModal,
			SaleOrder saleOrder, BigDecimal quantity, BigDecimal unitPrice,
			BigDecimal sum, String memo, Integer serialNumber,
			String productModalText, String productCategoryText,String productUnitsText) {
		this.id = id;
		this.productModal = productModal;
		this.saleOrder = saleOrder;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.sum = sum;
		this.memo = memo;
		this.serialNumber = serialNumber;
		this.productModalText = productModalText;
		this.productCategoryText = productCategoryText;
		this.productUnitsText = productUnitsText;
	}

	public String getProductUnitsText() {
		return productUnitsText;
	}

	public void setProductUnitsText(String productUnitsText) {
		this.productUnitsText = productUnitsText;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ProductModal getProductModal() {
		return this.productModal;
	}

	public void setProductModal(ProductModal productModal) {
		this.productModal = productModal;
	}

	public SaleOrder getSaleOrder() {
		return this.saleOrder;
	}

	public void setSaleOrder(SaleOrder saleOrder) {
		this.saleOrder = saleOrder;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public BigDecimal getSum() {
		return this.sum;
	}

	public void setSum(BigDecimal sum) {
		this.sum = sum;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Integer getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(Integer serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getProductModalText() {
		return this.productModalText;
	}

	public void setProductModalText(String productModalText) {
		this.productModalText = productModalText;
	}

	public String getProductCategoryText() {
		return this.productCategoryText;
	}

	public void setProductCategoryText(String productCategoryText) {
		this.productCategoryText = productCategoryText;
	}

}
